import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const IBMPlexSansFont = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const IBMPlexMonoFont = IBM_Plex_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${IBMPlexMonoFont.variable} ${IBMPlexSansFont.variable} font-mono`}
      >
        {children}
      </body>
    </html>
  );
}
